import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Question } from '../../../types';
import { RichTextEditor } from '../../../components/RichTextEditor';
import { Save, X, Wand2, Loader2, BookOpen, Upload, Image as ImageIcon, Trash2, Link as LinkIcon, Sparkles } from 'lucide-react';
import { useStore } from '../../../store/useStore';
import { api } from '../../../services/api';
import { generateQuizQuestion } from '../../../services/geminiService';

interface UnifiedQuestionBuilderProps {
  initialQuestion?: Partial<Question>;
  onSave: (question: Partial<Question>) => void;
  onCancel: () => void;
  subjectId?: string;
  sectionId?: string;
  generateOnOpen?: boolean;
  /** Restricts a contextual caller (such as interactive video) without changing the general question editor. */
  allowedTypes?: Question['type'][];
  isSaving?: boolean;
}

const emptyMcqOptions = ['', '', '', ''];

const normalizeQuestionType = (type?: Partial<Question>['type'] | string): Question['type'] => {
  if (type === 'true_false' || type === 'essay') return type;
  return 'mcq';
};

const normalizeQuestionForEditing = (source?: Partial<Question>, fallbackSubjectId = '', fallbackSectionId = ''): Partial<Question> => {
  const type = normalizeQuestionType(source?.type);
  const options =
    type === 'true_false'
      ? ['صح', 'خطأ']
      : type === 'essay'
        ? []
        : [...((source?.options || []).map((option) => String(option ?? ''))), ...emptyMcqOptions].slice(0, Math.max(4, source?.options?.length || 0));

  const resolvedSubject = (source as any)?.subjectId || source?.subject || fallbackSubjectId || '';
  const resolvedSectionId = (source as any)?.sectionId || (source as any)?.mainSkillId || fallbackSectionId || '';

  return {
    text: '',
    explanation: '',
    videoUrl: '',
    imageUrl: '',
    hint: '',
    solvingStrategy: '',
    description: '',
    tags: [],
    difficulty: 'Medium',
    pathId: source?.pathId || '',
    ...(source || {}),
    subject: resolvedSubject,
    sectionId: resolvedSectionId,
    type,
    options,
    correctOptionIndex: Math.max(0, Math.min(Number(source?.correctOptionIndex ?? 0), Math.max(options.length - 1, 0))),
  };
};

export const UnifiedQuestionBuilder: React.FC<UnifiedQuestionBuilderProps> = ({
  initialQuestion,
  onSave,
  onCancel,
  subjectId,
  sectionId,
  generateOnOpen = false,
  allowedTypes,
  isSaving = false,
}) => {
  const { skills, subjects, sections, paths } = useStore();
  const [isGenerating, setIsGenerating] = useState(false);
  const [isUploadingImage, setIsUploadingImage] = useState(false);
  const [showImageUrlInput, setShowImageUrlInput] = useState(false);
  const [showAiFields, setShowAiFields] = useState(Boolean(initialQuestion?.hint || initialQuestion?.solvingStrategy || initialQuestion?.description));
  const [validationError, setValidationError] = useState('');
  const [generationError, setGenerationError] = useState('');
  const [question, setQuestion] = useState<Partial<Question>>(() => normalizeQuestionForEditing(initialQuestion, subjectId || '', sectionId || ''));
  const [showPassageField, setShowPassageField] = useState(Boolean(initialQuestion?.passage));
  const hasAutoGenerated = useRef(false);

  const availableMainSkills = useMemo(
    () => sections.filter((section) => !!question.subject && section.subjectId === question.subject),
    [sections, question.subject]
  );

  const availableSubSkills = useMemo(
    () => skills.filter((skill) => !!question.subject && skill.subjectId === question.subject && (!question.sectionId || skill.sectionId === question.sectionId)),
    [skills, question.subject, question.sectionId]
  );

  const selectedSubSkills = useMemo(
    () => skills.filter((skill) => question.skillIds?.includes(skill.id)),
    [skills, question.skillIds]
  );

  useEffect(() => {
    setQuestion(normalizeQuestionForEditing(initialQuestion, subjectId || '', sectionId || ''));
  }, [initialQuestion?.id, subjectId, sectionId]);

  useEffect(() => {
    if (!question.subject) return;

    const currentSubject = subjects.find((subject) => subject.id === question.subject);
    if (!currentSubject) return;

    const nextPathId = currentSubject.pathId;
    if (sections.length === 0 || skills.length === 0) return;

    const sectionBelongsToSubject = !question.sectionId || sections.some(
      (section) => section.id === question.sectionId && section.subjectId === question.subject
    );

    if (question.pathId !== nextPathId || !sectionBelongsToSubject) {
      setQuestion((prev) => ({
        ...prev,
        pathId: nextPathId,
        sectionId: sectionBelongsToSubject ? prev.sectionId : '',
      }));
    }
  }, [question.subject, subjects, sections, skills]);

  const handleUploadImageFile = async (file: File) => {
    if (!file.type.startsWith('image/')) {
      setValidationError('يرجى اختيار ملف صورة صالح (PNG, JPEG, WebP).');
      return;
    }
    if (file.size > 5 * 1024 * 1024) {
      setValidationError('حجم الصورة يجب ألا يتجاوز 5 ميجابايت.');
      return;
    }

    setIsUploadingImage(true);
    setValidationError('');
    try {
      const reader = new FileReader();
      reader.onload = async () => {
        try {
          const base64 = reader.result as string;
          const res = await api.uploadQuestionImage({
            imageBase64: base64,
            filename: file.name,
            folder: 'custom'
          });
          if (res?.imageUrl) {
            setQuestion(prev => ({ ...prev, imageUrl: res.imageUrl }));
          }
        } catch (err) {
          setValidationError(err instanceof Error ? err.message : 'تعذر رفع الصورة إلى الخادم.');
        } finally {
          setIsUploadingImage(false);
        }
      };
      reader.readAsDataURL(file);
    } catch {
      setIsUploadingImage(false);
      setValidationError('تعذر قراءة ملف الصورة.');
    }
  };

  const handleContainerPaste = async (e: React.ClipboardEvent) => {
    const items = e.clipboardData?.items;
    if (!items) return;
    for (let i = 0; i < items.length; i++) {
      if (items[i].type.indexOf('image') !== -1) {
        const file = items[i].getAsFile();
        if (file) {
          e.preventDefault();
          await handleUploadImageFile(file);
          break;
        }
      }
    }
  };

  const handleSave = () => {
    handleValidatedSave();
    return;
  };

  const handleGenerate = async () => {
    await handleGenerateWithFeedback();
    return;
  };

  const handleValidatedSave = () => {
    if (!question.text?.trim() && !question.imageUrl?.trim()) {
      setValidationError('يرجى إدخال نص السؤال أو إرفاق صورة للسؤال.');
      return;
    }
    if (!question.pathId) {
      setValidationError('يرجى اختيار المسار.');
      return;
    }
    if (!question.subject) {
      setValidationError('يرجى اختيار المادة.');
      return;
    }
    if (!question.sectionId) {
      setValidationError('يرجى اختيار المهارة الرئيسة.');
      return;
    }
    if (!question.skillIds || question.skillIds.length === 0) {
      setValidationError('يرجى ربط السؤال بمهارة فرعية واحدة على الأقل.');
      return;
    }
    const optionRows = (question.options || [])
      .map((option, index) => ({ index, value: String(option || '').trim() }))
      .filter((option) => option.value);
    const trimmedOptions = optionRows.map((option) => option.value);
    const selectedCorrectIndex = Number(question.correctOptionIndex ?? 0);
    const normalizedCorrectOptionIndex = optionRows.findIndex((option) => option.index === selectedCorrectIndex);

    if (question.type === 'mcq' && trimmedOptions.length < 2) {
      setValidationError('يرجى إدخال اختيارين على الأقل.');
      return;
    }
    if (question.type === 'mcq' && normalizedCorrectOptionIndex < 0) {
      setValidationError('يرجى اختيار إجابة صحيحة من الاختيارات الموجودة.');
      return;
    }

    setValidationError('');
    onSave({
      ...question,
      text: question.text || '',
      imageUrl: question.imageUrl?.trim() || undefined,
      description: question.description?.trim() || undefined,
      hint: question.hint?.trim() || undefined,
      solvingStrategy: question.solvingStrategy?.trim() || undefined,
      tags: question.tags || [],
      passage: question.passage?.trim() || undefined,
      options: question.type === 'essay' ? [] : question.type === 'true_false' ? ['صح', 'خطأ'] : trimmedOptions,
      correctOptionIndex: question.type === 'essay' ? 0 : question.type === 'true_false' ? Number(question.correctOptionIndex ?? 0) : normalizedCorrectOptionIndex,
    });
  };

  const handleGenerateWithFeedback = async () => {
    setGenerationError('');
    setIsGenerating(true);

    let topicName = 'القدرات العامة';

    if (question.subject) {
      const subjectName = subjects.find((subject) => subject.id === question.subject)?.name;
      if (subjectName) topicName = subjectName;
    } else if (question.pathId) {
      const pathName = paths.find((path) => path.id === question.pathId)?.name;
      if (pathName) topicName = pathName;
    }

    if (question.sectionId) {
      const mainSkill = sections.find((section) => section.id === question.sectionId)?.name;
      if (mainSkill) topicName += ` - ${mainSkill}`;
    }

    if (question.skillIds && question.skillIds.length > 0) {
      const subSkill = skills.find((item) => item.id === question.skillIds![0])?.name;
      if (subSkill) topicName += ` - ${subSkill}`;
    }

    try {
      const generated = await generateQuizQuestion(topicName);
      if (generated) {
        setQuestion((prev) => ({
          ...prev,
          text: generated.question,
          options: generated.options,
          correctOptionIndex: generated.correctIndex,
          explanation: generated.explanation,
          type: 'mcq'
        }));
      }
    } catch (error) {
      console.error(error);
      setGenerationError('حدث خطأ أثناء التوليد. جرّب مرة أخرى بعد تحديد المادة والمهارة.');
    } finally {
      setIsGenerating(false);
    }
  };

  useEffect(() => {
    if (!generateOnOpen || hasAutoGenerated.current) return;
    hasAutoGenerated.current = true;
    void handleGenerateWithFeedback();
  }, [generateOnOpen]);

  const modalContent = (
    <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-[9999] flex items-center justify-center p-3 sm:p-6 overflow-y-auto animate-fade-in" dir="rtl">
      <div className="bg-white rounded-2xl w-full max-w-6xl max-h-[92vh] overflow-hidden shadow-2xl flex flex-col my-auto border border-slate-200" data-testid="question-builder-modal">
        <div className="p-4 border-b border-gray-100 flex justify-between items-center bg-gray-50/90 sticky top-0 z-10">
          <h3 className="font-bold text-gray-800 text-lg flex items-center gap-2">
            منشئ الأسئلة الموحد
          </h3>
          <button onClick={onCancel} className="text-gray-400 hover:text-gray-600 p-1.5 rounded-lg hover:bg-gray-200 transition-colors" title="إغلاق">
            <X size={20} />
          </button>
        </div>

        <div className="p-4 sm:p-6 overflow-y-auto flex-1 space-y-5" onPaste={handleContainerPaste}>
          {validationError && (
            <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-medium text-red-700">
              {validationError}
            </div>
          )}
          {generationError && (
            <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-medium text-amber-700">
              {generationError}
            </div>
          )}

          {/* قسم صورة السؤال مع المعاينة والرفع المباشر وCtrl+V */}
          <div className="rounded-2xl border border-indigo-100 bg-indigo-50/30 p-4 space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-sm font-bold text-indigo-900">
                <ImageIcon size={18} className="text-indigo-600" />
                <span>صورة السؤال (تظهر كبطاقة في بنك الأسئلة والاختبارات)</span>
              </div>
              <span className="text-xs text-indigo-600 font-semibold">تدعم اللصق المباشر (Ctrl + V) من لقطة الشاشة</span>
            </div>

            {question.imageUrl ? (
              <div className="space-y-3">
                <div className="relative group overflow-hidden rounded-xl border border-indigo-200 bg-white p-2 flex items-center justify-center max-h-72">
                  <img
                    src={question.imageUrl}
                    alt="صورة السؤال"
                    className="max-h-64 max-w-full object-contain rounded-lg"
                  />
                </div>
                <div className="flex items-center gap-2 flex-wrap">
                  <label className="cursor-pointer inline-flex items-center gap-1.5 px-3 py-1.5 bg-indigo-50 text-indigo-700 hover:bg-indigo-100 border border-indigo-200 rounded-lg text-xs font-bold transition-colors">
                    <Upload size={14} />
                    {isUploadingImage ? 'جارٍ الرفع لكلاود فلير...' : 'استبدال الصورة'}
                    <input
                      type="file"
                      accept="image/*"
                      className="hidden"
                      onChange={e => {
                        const file = e.target.files?.[0];
                        if (file) void handleUploadImageFile(file);
                        e.target.value = '';
                      }}
                    />
                  </label>
                  <button
                    type="button"
                    onClick={() => setQuestion(prev => ({ ...prev, imageUrl: '' }))}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-red-50 text-red-600 hover:bg-red-100 border border-red-200 rounded-lg text-xs font-bold transition-colors"
                  >
                    <Trash2 size={14} />
                    حذف الصورة
                  </button>
                  <a
                    href={question.imageUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex items-center gap-1 text-xs text-slate-500 hover:underline ms-auto font-mono dir-ltr"
                  >
                    {question.imageUrl.slice(0, 45)}...
                  </a>
                </div>
              </div>
            ) : (
              <div className="border-2 border-dashed border-indigo-200 rounded-xl p-5 text-center bg-white/70 hover:bg-white transition-colors">
                <div className="flex flex-col items-center gap-2">
                  <div className="p-3 bg-indigo-50 rounded-full text-indigo-600">
                    <Upload size={22} />
                  </div>
                  <div className="text-sm font-bold text-gray-800">
                    اسحب الصورة وأفلتها هنا، أو اضغط للاختيار من جهازك
                  </div>
                  <div className="text-xs text-indigo-600 font-semibold bg-indigo-50/80 px-3 py-1 rounded-full">
                    💡 نصيحة: يمكنك التقاط لقطة شاشة والضغط مباشرة على (Ctrl + V) للصقها هنا!
                  </div>
                  <div className="flex items-center gap-3 mt-2">
                    <label className="cursor-pointer inline-flex items-center gap-1.5 px-4 py-2 bg-indigo-600 text-white hover:bg-indigo-700 rounded-xl text-xs font-bold transition-colors shadow-xs">
                      {isUploadingImage ? <Loader2 size={14} className="animate-spin" /> : <Upload size={14} />}
                      {isUploadingImage ? 'جارٍ رفع الصورة لكلاود فلير...' : 'اختيار صورة من الجهاز'}
                      <input
                        type="file"
                        accept="image/*"
                        className="hidden"
                        onChange={e => {
                          const file = e.target.files?.[0];
                          if (file) void handleUploadImageFile(file);
                          e.target.value = '';
                        }}
                      />
                    </label>
                    <button
                      type="button"
                      onClick={() => setShowImageUrlInput(!showImageUrlInput)}
                      className="inline-flex items-center gap-1 px-3 py-2 text-slate-600 hover:bg-slate-100 border border-slate-200 rounded-xl text-xs font-bold transition-colors"
                    >
                      <LinkIcon size={13} />
                      رابط صورة مباشر
                    </button>
                  </div>
                  {showImageUrlInput && (
                    <div className="w-full mt-3 flex items-center gap-2">
                      <input
                        type="text"
                        placeholder="https://pub-...r2.dev/..."
                        className="flex-1 px-3 py-1.5 text-xs border border-slate-300 rounded-lg text-left dir-ltr"
                        onKeyDown={e => {
                          if (e.key === 'Enter') {
                            setQuestion(prev => ({ ...prev, imageUrl: (e.target as HTMLInputElement).value.trim() }));
                          }
                        }}
                      />
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>

          {/* حقل القطعة القرائية (استيعاب المقروء) - اختياري */}
          <div className="border border-amber-200/80 bg-amber-50/40 rounded-xl p-3.5 space-y-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-xs font-bold text-amber-900">
                <BookOpen size={16} className="text-amber-700" />
                <span>النص القرائي / قطعة الفهم (استيعاب المقروء - اختياري)</span>
              </div>
              <button
                type="button"
                onClick={() => setShowPassageField(!showPassageField)}
                className="text-xs text-amber-800 font-bold hover:underline cursor-pointer"
              >
                {showPassageField ? 'إخفاء القطعة' : '+ إضافة قطعة للسؤال'}
              </button>
            </div>
            {showPassageField && (
              <div>
                <p className="text-[11px] text-amber-700/90 mb-1.5">
                  أدخل نص القطعة هنا. ستظهر للطالب في لوحة مخصصة ومريحة للقراءة بجانب السؤال مع إمكانية تكبير الخط والتمرير.
                </p>
                <textarea
                  value={question.passage || ''}
                  onChange={e => setQuestion(prev => ({ ...prev, passage: e.target.value }))}
                  rows={4}
                  placeholder="أدخل نص القطعة أو المقال القرائي هنا..."
                  dir="rtl"
                  className="w-full px-3 py-2 border border-amber-300 rounded-lg text-sm bg-white focus:outline-none focus:border-amber-500 font-normal leading-relaxed"
                />
              </div>
            )}
          </div>

          <div className="flex justify-between items-center">
            <label className="block text-sm font-bold text-gray-700">نص السؤال</label>
            <button
              onClick={handleGenerateWithFeedback}
              disabled={isGenerating}
              className="text-xs bg-indigo-50 text-indigo-600 px-3 py-1.5 rounded-lg font-bold flex items-center gap-1 hover:bg-indigo-100 disabled:opacity-50 transition-colors cursor-pointer"
            >
              {isGenerating ? <Loader2 size={14} className="animate-spin" /> : <Wand2 size={14} />}
              {isGenerating ? 'جارٍ التوليد...' : 'توليد بالذكاء الاصطناعي'}
            </button>
          </div>
          <RichTextEditor
            value={question.text || ''}
            onChange={value => setQuestion(prev => ({ ...prev, text: value }))}
            minHeightClass="min-h-[360px] [&_.ql-container]:min-h-[310px]"
          />

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-bold text-gray-700 mb-2">نوع السؤال</label>
              <select
                value={question.type || 'mcq'}
                onChange={event => {
                  const nextType = event.target.value as Question['type'];
                  setQuestion(prev => ({
                    ...prev,
                    type: nextType,
                    options: nextType === 'true_false' ? ['صح', 'خطأ'] : nextType === 'essay' ? [] : (prev.options?.length ? prev.options : emptyMcqOptions),
                    correctOptionIndex: nextType === 'essay' ? 0 : Math.min(Number(prev.correctOptionIndex ?? 0), nextType === 'true_false' ? 1 : Math.max((prev.options?.length || 4) - 1, 0)),
                  }));
                }}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
              >
                {(!allowedTypes || allowedTypes.includes('mcq')) && <option value="mcq">اختيار من متعدد</option>}
                {(!allowedTypes || allowedTypes.includes('true_false')) && <option value="true_false">صح أم خطأ</option>}
                {(!allowedTypes || allowedTypes.includes('essay')) && <option value="essay">مقالي / نصي</option>}
              </select>
            </div>
            <div>
              <label className="block text-sm font-bold text-gray-700 mb-2">مستوى الصعوبة</label>
              <select
                value={question.difficulty || 'Medium'}
                onChange={event => setQuestion(prev => ({ ...prev, difficulty: event.target.value as Question['difficulty'] }))}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
              >
                <option value="Easy">سهل</option>
                <option value="Medium">متوسط</option>
                <option value="Hard">صعب</option>
              </select>
            </div>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            <div className="col-span-2 md:col-span-1">
              <label className="block text-sm font-bold text-gray-700 mb-2">المسار</label>
              <select
                value={question.pathId || ''}
                onChange={event => setQuestion({ ...question, pathId: event.target.value, subject: '', sectionId: '', skillIds: [] })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
              >
                <option value="">-- اختر المسار --</option>
                {paths.map(path => (
                  <option key={path.id} value={path.id}>{path.name}</option>
                ))}
              </select>
            </div>
            <div className="col-span-2 md:col-span-1">
              <label className="block text-sm font-bold text-gray-700 mb-2">المادة</label>
              <select
                value={question.subject || ''}
                onChange={event => setQuestion({ ...question, subject: event.target.value, sectionId: '', skillIds: [] })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
                disabled={!question.pathId || subjects.filter(subject => subject.pathId === question.pathId).length === 0}
              >
                <option value="">{!question.pathId ? '-- اختر المسار أولًا --' : '-- اختر المادة --'}</option>
                {subjects.filter(subject => subject.pathId === question.pathId).map(subject => (
                  <option key={subject.id} value={subject.id}>{subject.name}</option>
                ))}
              </select>
            </div>
            <div className="col-span-2 md:col-span-1">
              <label className="block text-sm font-bold text-gray-700 mb-2">المهارة الرئيسة</label>
              <select
                value={question.sectionId || ''}
                onChange={event => setQuestion({ ...question, sectionId: event.target.value, skillIds: [] })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
                disabled={!question.subject}
              >
                <option value="">-- اختر المهارة الرئيسة --</option>
                {availableMainSkills.map(section => (
                  <option key={section.id} value={section.id}>{section.name}</option>
                ))}
              </select>
            </div>
            <div className="col-span-2">
              <label className="block text-sm font-bold text-gray-700 mb-2">ربط بالمهارات الفرعية</label>
              <div className="flex flex-wrap gap-2 mb-2">
                {selectedSubSkills.map(subSkill => (
                  <span key={subSkill.id} className="bg-indigo-100 text-indigo-800 px-2 py-1 rounded-lg text-sm flex items-center gap-1">
                    {subSkill.name}
                    <button
                      onClick={() => setQuestion(prev => ({ ...prev, skillIds: prev.skillIds?.filter(id => id !== subSkill.id) }))}
                      className="text-indigo-600 hover:text-indigo-900"
                    >
                      <X size={14} />
                    </button>
                  </span>
                ))}
              </div>
              <select
                value=""
                onChange={event => {
                  if (event.target.value && !question.skillIds?.includes(event.target.value)) {
                    setQuestion(prev => ({ ...prev, skillIds: [...(prev.skillIds || []), event.target.value] }));
                  }
                }}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
                disabled={!question.subject || !question.sectionId || availableSubSkills.length === 0}
              >
                <option value="">
                  {!question.subject
                    ? '-- اختر المادة أولًا --'
                    : !question.sectionId
                      ? '-- اختر المهارة الرئيسة أولًا --'
                      : availableSubSkills.length === 0
                        ? '-- لا توجد مهارات فرعية لهذه المهارة الرئيسة بعد --'
                        : '-- أضف مهارة فرعية --'}
                </option>
                {availableSubSkills.map(subSkill => (
                  <option key={subSkill.id} value={subSkill.id}>{subSkill.name}</option>
                ))}
              </select>
              <p className="text-xs text-gray-500 mt-1">المهارات هنا تُسحب من مركز المهارات الحقيقي: المهارة الرئيسة ثم المهارات الفرعية التابعة لها.</p>
            </div>
            <div>
              <label className="block text-sm font-bold text-gray-700 mb-2">رابط فيديو الشرح (اختياري)</label>
              <input
                type="text"
                value={question.videoUrl || ''}
                onChange={event => setQuestion(prev => ({ ...prev, videoUrl: event.target.value }))}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
                placeholder="https://..."
              />
            </div>
          </div>

          {question.type === 'mcq' && (
            <div className="space-y-3">
              <label className="block text-sm font-bold text-gray-700">الخيارات</label>
              {(question.options?.length ? question.options : emptyMcqOptions).map((option, index) => (
                <div key={index} className="flex items-center gap-3">
                  <input
                    type="radio"
                    name="correctOption"
                    checked={question.correctOptionIndex === index}
                    onChange={() => setQuestion(prev => ({ ...prev, correctOptionIndex: index }))}
                    className="w-5 h-5 text-emerald-600 focus:ring-emerald-500"
                  />
                  <input
                    type="text"
                    value={option}
                    data-testid="question-builder-option-input"
                    onChange={event => {
                      const newOptions = [...(question.options || [])];
                      newOptions[index] = event.target.value;
                      setQuestion(prev => ({ ...prev, options: newOptions }));
                    }}
                    className={`flex-1 border rounded-lg px-4 py-2 focus:ring-2 focus:ring-indigo-500 ${question.correctOptionIndex === index ? 'border-emerald-500 bg-emerald-50' : 'border-gray-300'}`}
                    placeholder={`الخيار ${index + 1}`}
                  />
                </div>
              ))}
              <p className="text-xs text-gray-500 mt-2">اختر الزر الدائري بجانب الإجابة الصحيحة.</p>
            </div>
          )}

          {question.type === 'true_false' && (
            <div className="space-y-3">
              <label className="block text-sm font-bold text-gray-700">الإجابة الصحيحة</label>
              <div className="flex gap-4">
                <label className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="radio"
                    name="tf"
                    checked={question.correctOptionIndex === 0}
                    onChange={() => setQuestion(prev => ({ ...prev, correctOptionIndex: 0, options: ['صح', 'خطأ'] }))}
                    className="w-5 h-5 text-emerald-600"
                  />
                  <span className="font-bold">صح</span>
                </label>
                <label className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="radio"
                    name="tf"
                    checked={question.correctOptionIndex === 1}
                    onChange={() => setQuestion(prev => ({ ...prev, correctOptionIndex: 1, options: ['صح', 'خطأ'] }))}
                    className="w-5 h-5 text-emerald-600"
                  />
                  <span className="font-bold">خطأ</span>
                </label>
              </div>
            </div>
          )}

          {/* قسم بيانات المدرب الذكي والبيانات المتقدمة (AI Coach & Advanced Metadata) */}
          <div className="rounded-2xl border border-indigo-200/80 bg-gradient-to-br from-indigo-50/40 via-white to-purple-50/30 p-4 space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="p-1.5 rounded-lg bg-indigo-100 text-indigo-700 font-bold">🤖</span>
                <div>
                  <h4 className="text-sm font-bold text-slate-800">بيانات المدرب الذكي وتوجيه الحل (AI Coach)</h4>
                  <p className="text-xs text-slate-500">تلميحات وإستراتيجيات الحل التي يعتمد عليها الذكاء الاصطناعي لتوجيه الطالب</p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => setShowAiFields(!showAiFields)}
                className="text-xs font-bold text-indigo-700 hover:text-indigo-900 bg-white border border-indigo-200 px-3 py-1.5 rounded-lg transition-colors cursor-pointer shadow-2xs"
              >
                {showAiFields ? 'إخفاء الحقول' : '+ تعديل التلميح والإستراتيجية والوسوم'}
              </button>
            </div>

            {showAiFields && (
              <div className="space-y-4 pt-2 border-t border-indigo-100/80">
                {/* وصف/عنوان السؤال */}
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    عنوان أو موضوع السؤال المختصر (اختياري)
                  </label>
                  <input
                    type="text"
                    value={question.description || ''}
                    onChange={e => setQuestion(prev => ({ ...prev, description: e.target.value }))}
                    placeholder="مثال: مقارنة بين الجذور، أو مسألة الأعمار وحساب الفرق"
                    className="w-full px-3 py-2 text-sm border border-slate-300 rounded-xl focus:ring-2 focus:ring-indigo-500 bg-white"
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {/* تلميح المدرب الذكي */}
                  <div>
                    <label className="flex items-center gap-1.5 text-xs font-bold text-amber-900 mb-1">
                      <span>💡 تلميح المدرب الذكي (AI Hint)</span>
                    </label>
                    <textarea
                      rows={3}
                      value={question.hint || ''}
                      onChange={e => setQuestion(prev => ({ ...prev, hint: e.target.value }))}
                      placeholder="تلميح خطوة أولى دون حرق الحل (مثال: تذكر أن جذر س + ص لا يساوي جذر س + جذر ص...)"
                      className="w-full px-3 py-2 text-xs border border-amber-200 rounded-xl focus:ring-2 focus:ring-amber-500 bg-white leading-relaxed"
                    />
                  </div>

                  {/* إستراتيجية الحل */}
                  <div>
                    <label className="flex items-center gap-1.5 text-xs font-bold text-emerald-900 mb-1">
                      <span>⚡ إستراتيجية الحل (Solving Strategy)</span>
                    </label>
                    <textarea
                      rows={3}
                      value={question.solvingStrategy || ''}
                      onChange={e => setQuestion(prev => ({ ...prev, solvingStrategy: e.target.value }))}
                      placeholder="مثال: تبسيط الجذور، أو الرسم الهندسي السريع، أو التجريب الذكي للخيارات..."
                      className="w-full px-3 py-2 text-xs border border-emerald-200 rounded-xl focus:ring-2 focus:ring-emerald-500 bg-white leading-relaxed"
                    />
                  </div>
                </div>

                {/* وسوم السؤال */}
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    🏷️ الوسوم والمرجع (مفصولة بفواصل)
                  </label>
                  <input
                    type="text"
                    value={(question.tags || []).join(', ')}
                    onChange={e => {
                      const tagsArray = e.target.value
                        .split(',')
                        .map(t => t.trim())
                        .filter(Boolean);
                      setQuestion(prev => ({ ...prev, tags: tagsArray }));
                    }}
                    placeholder="مثال: كتاب_تجميعات_2026, صفحة_8, سؤال_18, مقارنات"
                    className="w-full px-3 py-2 text-xs border border-slate-300 rounded-xl focus:ring-2 focus:ring-indigo-500 bg-white"
                  />
                  <p className="text-[11px] text-slate-400 mt-1">
                    تساعد الوسوم في تنظيم الأسئلة وربطها برقم الصفحة والسؤال في الكتاب المصدري.
                  </p>
                </div>
              </div>
            )}
          </div>

          <div>
            <label className="block text-sm font-bold text-gray-700 mb-2">شرح الإجابة (اختياري)</label>
            <RichTextEditor
              value={question.explanation || ''}
              onChange={value => setQuestion(prev => ({ ...prev, explanation: value }))}
              minHeightClass="h-52"
            />
          </div>
        </div>

        <div className="p-4 sm:px-6 border-t border-gray-100 bg-gray-50 flex justify-end gap-3 sticky bottom-0 z-10">
          <button
            type="button"
            onClick={onCancel}
            className="px-5 py-2.5 text-gray-700 bg-white border border-gray-200 font-bold hover:bg-gray-100 rounded-xl transition-colors cursor-pointer"
          >
            إلغاء
          </button>
          <button
            type="button"
            onClick={handleValidatedSave}
            disabled={isSaving}
            data-testid="question-builder-save"
            className="px-6 py-2.5 bg-indigo-600 text-white font-bold rounded-xl hover:bg-indigo-700 transition-colors flex items-center gap-2 disabled:cursor-not-allowed disabled:opacity-60 shadow-sm cursor-pointer"
          >
            <Save size={18} /> {isSaving ? 'جارٍ حفظ السؤال...' : 'حفظ السؤال'}
          </button>
        </div>
      </div>
    </div>
  );

  return typeof document !== 'undefined' ? createPortal(modalContent, document.body) : modalContent;
};
