import React, { useEffect, useState } from 'react';
import { CheckCircle2, Loader2, RotateCcw as SendBack, Search, ShieldCheck, XCircle } from 'lucide-react';
import { api } from '../../services/api';

type ReviewItem = { id: string; type: 'course' | 'lesson' | 'question' | 'quiz' | 'library'; title: string; ownerId: string; pathId: string; subjectId: string };
const labels: Record<ReviewItem['type'], string> = { course: 'دورة', lesson: 'درس/فيديو', question: 'سؤال', quiz: 'اختبار', library: 'ملف مكتبة' };

export const ContentReviewQueueManager: React.FC = () => {
  const [items, setItems] = useState<ReviewItem[]>([]); const [type, setType] = useState(''); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const params = new URLSearchParams({ limit: '100' }); if (type) params.set('type', type); if (search.trim()) params.set('search', search.trim()); const response = await api.get<{ items: ReviewItem[] }>(`/content/review-queue?${params}`); setItems(response.items || []); } catch { setError('تعذر تحميل قائمة الاعتماد.'); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => void load(), 180); return () => window.clearTimeout(timer); }, [type, search]);
  const decide = async (item: ReviewItem, decision: 'approved' | 'rejected') => { const reviewerNotes = window.prompt(decision === 'approved' ? 'ملاحظة للمدرب (اختيارية):' : 'اشرح المطلوب تعديله:'); if (reviewerNotes === null) return; try { await api.patch(`/content/review-queue/${item.type}/${item.id}`, { decision, reviewerNotes, publish: decision === 'approved' && item.type !== 'question' }); await load(); } catch { setError('تعذر حفظ قرار المراجعة.'); } };
  return <div className="space-y-6" dir="rtl"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-2xl font-black text-gray-900">مركز اعتماد المحتوى</h2><p className="mt-1 text-sm text-gray-500">قائمة خادمية موحدة للمحتوى المرسل من المدربين. القرار مسجل باسم المدير.</p></div><div className="inline-flex items-center gap-2 rounded-xl bg-indigo-50 px-4 py-2 text-sm font-bold text-indigo-700"><ShieldCheck size={17}/>Admin فقط</div></div><div className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-2"><label className="relative"><Search className="absolute right-3 top-3 text-gray-400" size={16}/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="ابحث بالعنوان" className="w-full rounded-xl border py-2 pr-9 pl-3 text-sm"/></label><select value={type} onChange={(e) => setType(e.target.value)} className="rounded-xl border px-3 py-2 text-sm"><option value="">كل الأنواع</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>{error ? <div className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div> : null}<div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-right text-sm"><thead className="bg-gray-50 text-gray-600"><tr><th className="p-4">العنصر</th><th className="p-4">النوع</th><th className="p-4">المدرب</th><th className="p-4">القرار</th></tr></thead><tbody className="divide-y">{loading ? <tr><td colSpan={4} className="p-10 text-center"><Loader2 className="mx-auto animate-spin"/></td></tr> : items.map((item) => <tr key={`${item.type}-${item.id}`}><td className="p-4 font-bold">{item.title}</td><td className="p-4">{labels[item.type]}</td><td className="p-4 text-xs text-gray-500">{item.ownerId || 'غير محدد'}</td><td className="p-4"><div className="flex gap-2"><button onClick={() => void decide(item, 'approved')} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white"><CheckCircle2 size={14}/>اعتماد</button><button onClick={() => void decide(item, 'rejected')} className="inline-flex items-center gap-1 rounded-lg bg-rose-600 px-3 py-2 text-xs font-bold text-white"><XCircle size={14}/>طلب تعديل</button></div></td></tr>)}{!loading && !items.length ? <tr><td colSpan={4} className="p-10 text-center text-gray-500"><SendBack className="mx-auto mb-2"/>لا يوجد محتوى بانتظار الاعتماد.</td></tr> : null}</tbody></table></div></div>;
};
