import React, { useEffect, useState } from 'react';
import { CheckCircle2, PlusCircle, RefreshCw } from 'lucide-react';
import { api } from '../../services/api';

export const SmartClassroomInterventionPanel: React.FC = () => {
  const [intelligence, setIntelligence] = useState<any>(null); const [interventions, setInterventions] = useState<any[]>([]); const [pathId, setPathId] = useState(''); const [minimumEvidence, setMinimumEvidence] = useState('3'); const [selected, setSelected] = useState<any>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { const [data, records] = await Promise.all([api.getSupervisorClassroomIntelligence(), api.getSupervisorInterventions()]); setIntelligence(data.intelligence); setInterventions(records.interventions || []); setMessage(''); } catch { setMessage('تعذر تحميل مركز التدخلات ضمن نطاقك.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const candidates = intelligence?.schoolPerformance?.smartClassroom?.weakStudents || [];
  const create = async () => { const weakestSkill = intelligence?.schoolPerformance?.smartClassroom?.skillHeatmap?.[0]?.skillId; if (!selected || !pathId.trim() || !weakestSkill || !selected.schoolId || !selected.classId) { setMessage('اختر طالبًا وأدخل معرّف مسار؛ يلزم وجود دليل مهارة وفصل صالحين.'); return; } setSaving(true); try { await api.createSupervisorIntervention({ schoolId: selected.schoolId, classId: selected.classId, skillId: weakestSkill, targetStudentIds: [selected.studentId], pathId: pathId.trim(), minimumEvidence: Number(minimumEvidence) || undefined }); setMessage('تم إسناد المسار العلاجي وربط baseline بالتدخل.'); await load(); } catch { setMessage('تعذر إنشاء التدخل؛ تحقق من المسار والنطاق ووحدة العقد.'); } finally { setSaving(false); } };
  const showOutcome = async (id: string) => { try { const result = await api.getSupervisorInterventionOutcome(id); setMessage(result.comparison?.confidence === 'measured' ? `التغير المثبت: ${result.comparison.delta ?? '—'} نقطة.` : 'توجد بيانات متابعة، لكنها لم تبلغ الحد الأدنى للأدلة بعد.'); } catch { setMessage('تعذر قراءة نتيجة التدخل ضمن نطاقك.'); } };
  return <section className="rounded-2xl border border-emerald-100 bg-emerald-50/40 p-5 shadow-sm" dir="rtl"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-black text-emerald-950"><PlusCircle size={19} /> مركز التدخلات</h2><p className="mt-1 text-sm text-emerald-800">ضعف مثبت ← مسار علاجي قائم ← متابعة قبل/بعد.</p></div><button onClick={() => void load()} className="rounded-xl border border-emerald-200 bg-white px-3 py-2 text-sm font-bold text-emerald-700"><RefreshCw size={15} className="ml-1 inline" />تحديث</button></div>{message && <p className="mt-3 rounded-lg bg-white p-3 text-sm text-slate-700">{message}</p>}{loading ? <p className="mt-4 text-sm text-slate-500">جارٍ تحميل الأدلة…</p> : <><div className="mt-4 rounded-xl bg-white p-4"><h3 className="font-black text-slate-900">إنشاء تدخل بمسار علاجي</h3><div className="mt-3 grid gap-2 md:grid-cols-3"><select value={selected?.studentId || ''} onChange={(event) => setSelected(candidates.find((item: any) => item.studentId === event.target.value) || null)} className="rounded-lg border border-slate-200 p-2 text-sm"><option value="">اختر طالبًا يحتاج مراجعة</option>{candidates.map((student: any) => <option key={student.studentId} value={student.studentId}>{student.name} — {student.accuracy ?? '—'}%</option>)}</select><input value={pathId} onChange={(event) => setPathId(event.target.value)} placeholder="معرّف المسار العلاجي" className="rounded-lg border border-slate-200 p-2 text-sm"/><input value={minimumEvidence} onChange={(event) => setMinimumEvidence(event.target.value)} inputMode="numeric" placeholder="الحد الأدنى للأدلة" className="rounded-lg border border-slate-200 p-2 text-sm"/></div><button disabled={saving} onClick={() => void create()} className="mt-3 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-black text-white disabled:opacity-60">{saving ? 'جارٍ الإسناد…' : 'إسناد المسار العلاجي'}</button><p className="mt-2 text-xs text-slate-500">الحد الأدنى للأدلة قابل للضبط، ولا يصدر النظام حكم تحسن قبل استيفائه.</p></div><div className="mt-4 rounded-xl bg-white p-4"><h3 className="font-black text-slate-900">التدخلات النشطة</h3>{interventions.length ? <div className="mt-3 space-y-2">{interventions.map((item) => <div key={item._id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-50 p-3 text-sm"><span><b>{item.skillId}</b> · {item.targetStudentIds.length} طالب · مسار {item.actionRef}</span><button onClick={() => void showOutcome(item._id)} className="rounded-lg bg-emerald-100 px-3 py-1.5 font-bold text-emerald-800"><CheckCircle2 size={14} className="ml-1 inline" />قياس النتيجة</button></div>)}</div> : <p className="mt-3 text-sm text-slate-500">لا توجد تدخلات في نطاقك بعد.</p>}</div></>}</section>;
};
