import React, { useEffect, useState } from 'react';
import { Download, Printer, Radio, RefreshCw } from 'lucide-react';
import { api } from '../../services/api';

export const SmartClassroomReportsPanel: React.FC = () => {
  const [sessions, setSessions] = useState<any[]>([]); const [selected, setSelected] = useState<any>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); setError(''); try { const result = await api.getSupervisorClassroomHistory(); setSessions(result.sessions || []); } catch { setError('تعذر تحميل تقارير الفصول الذكية ضمن نطاقك.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const openReport = async (id: string) => { try { const result = await api.getSupervisorClassroomReport(id); setSelected(result.report); } catch { setError('تعذر فتح تقرير الجلسة.'); } };
  const exportExcel = () => { if (!selected) return; const rows = selected.questions.map((q: any) => `<tr><td>${q.text}</td><td>${(q.skillIds || []).join('، ')}</td><td>${q.answered}</td><td>${q.correct}</td><td>${q.wrong}</td><td>${q.unanswered}</td></tr>`).join(''); const blob = new Blob([`<table><thead><tr><th>السؤال</th><th>المهارات</th><th>أجاب</th><th>صحيح</th><th>خطأ</th><th>غير مجاب</th></tr></thead><tbody>${rows}</tbody></table>`], { type: 'application/vnd.ms-excel' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `smart-classroom-${selected.sessionId}.xls`; link.click(); URL.revokeObjectURL(url); };
  return <section className="rounded-2xl border border-indigo-100 bg-indigo-50/30 p-5 shadow-sm print:bg-white" dir="rtl"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-black text-indigo-950"><Radio size={18} /> الفصول الذكية</h2><p className="mt-1 text-sm text-indigo-800">جلسات اليوم والسجل التشغيلي ضمن نطاق الإشراف فقط.</p></div><button onClick={() => void load()} className="print:hidden rounded-xl border border-indigo-200 bg-white px-3 py-2 text-sm font-bold text-indigo-700"><RefreshCw size={15} className="inline ml-1" />تحديث</button></div>{error && <p className="mt-3 text-sm text-rose-700">{error}</p>}{loading ? <p className="mt-4 text-sm text-slate-500">جارٍ تحميل الجلسات…</p> : <div className="mt-4 space-y-2">{sessions.length === 0 ? <p className="rounded-xl bg-white p-4 text-sm text-slate-500">لا توجد جلسات ذكية في نطاقك بعد.</p> : sessions.map((session) => <button key={session.sessionId} onClick={() => void openReport(session.sessionId)} className="flex w-full items-center justify-between rounded-xl bg-white p-4 text-right hover:bg-indigo-50"><span><b>{session.status === 'ended' ? 'جلسة منتهية' : 'جلسة جارية'}</b><small className="mt-1 block text-slate-500">منضم: {session.roster.joined} · إجابات: {session.totals.responses}</small></span><span className="text-xs text-slate-500">{new Date(session.startedAt).toLocaleString('ar-SA')}</span></button>)}</div>}{selected && <div className="mt-5 rounded-xl border border-indigo-100 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black text-slate-900">تقرير الجلسة</h3><p className="text-sm text-slate-600">المتوقع {selected.roster.expected} · المنضم {selected.roster.joined} · الغائب {selected.roster.absentFromSession}</p></div><div className="flex gap-2 print:hidden"><button onClick={exportExcel} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-bold text-white"><Download size={15} className="inline ml-1" />Excel</button><button onClick={() => window.print()} className="rounded-lg bg-slate-800 px-3 py-2 text-sm font-bold text-white"><Printer size={15} className="inline ml-1" />PDF</button></div></div><div className="mt-4 overflow-x-auto"><table className="w-full text-right text-sm"><thead><tr className="border-b"><th>السؤال</th><th>أجاب</th><th>صحيح</th><th>خطأ</th><th>غير مجاب</th></tr></thead><tbody>{selected.questions.map((q: any) => <tr key={q.questionId} className="border-b border-slate-100"><td className="py-3">{q.text}</td><td>{q.answered}</td><td>{q.correct}</td><td>{q.wrong}</td><td>{q.unanswered}</td></tr>)}</tbody></table></div></div>}</section>;
};
