import { z } from "zod";

export const quizSchema = z.object({
  id: z.string().optional(),
  title: z.string().min(1),
  description: z.string().optional(),
  pathId: z.string().min(1),
  subjectId: z.string().min(1),
  sectionId: z.string().nullable().optional(),
  type: z.enum(["quiz", "bank"]).default("quiz"),
  quizKind: z.enum(["drill", "test", "mock"]).default("test"),
  placement: z.enum(["training", "mock", "both"]).optional(),
  showInTraining: z.boolean().optional(),
  showInMock: z.boolean().optional(),
  learningPlacements: z.array(z.object({
    pathId: z.string().min(1),
    subjectId: z.string().optional().default(""),
    slot: z.enum(["training", "tests", "foundation", "course"]),
    accessType: z.enum(["inherit", "free", "paid", "package"]).optional().default("inherit"),
    isVisible: z.boolean().optional().default(true),
    order: z.number().optional().default(0),
    courseId: z.string().nullable().optional(),
    lessonId: z.string().nullable().optional(),
    topicId: z.string().nullable().optional(),
    createdAt: z.number().optional(),
    updatedAt: z.number().optional(),
  })).optional(),
  mode: z.enum(["regular", "saher", "central"]).default("regular"),
  assessmentData: z.object({
    // Default-off operational rollout control. Only directed or mock
    // assessments can activate this in the server-side mirror policy.
    mirrorSubmissions: z.boolean().default(false),
  }).optional(),
  settings: z.record(z.any()).optional().default({}),
  access: z.record(z.any()).optional().default({}),
  questionIds: z.array(z.string()).default([]),
  questions: z.array(z.any()).optional(),
  mockExam: z.object({
    enabled: z.boolean().default(false),
    pathId: z.string().default(""),
    qiyasCategory: z.enum(["qudrat", "tahsili", "specialized"]).optional(),
    targetScore: z.number().min(0).max(100).optional(),
    isStrictSectionLock: z.boolean().optional(),
    sections: z.array(z.object({
      id: z.string().min(1),
      title: z.string().min(1),
      subjectId: z.string().optional().default(""),
      questionIds: z.array(z.string()).default([]),
      timeLimit: z.number().nullable().optional(),
      order: z.number().optional(),
      domain: z.enum(["quantitative", "verbal", "math", "physics", "chemistry", "biology", "general"]).optional(),
      isStrictSectionLock: z.boolean().optional(),
    })).default([]),
  }).optional(),
  skillIds: z.array(z.string()).optional(),
  targetGroupIds: z.array(z.string()).default([]),
  targetUserIds: z.array(z.string()).default([]),
  dueDate: z.string().nullable().optional(),
  supervisorMessage: z.string().nullable().optional(),
  isPublished: z.boolean().default(false),
  showOnPlatform: z.boolean().default(true),
  ownerType: z.enum(["platform", "teacher", "school"]).optional(),
  ownerId: z.string().optional(),
  createdBy: z.string().optional(),
  assignedTeacherId: z.string().optional(),
  approvalStatus: z.enum(["draft", "pending_review", "approved", "rejected"]).optional(),
  approvedBy: z.string().optional(),
  approvedAt: z.number().nullable().optional(),
  reviewerNotes: z.string().optional(),
  revenueSharePercentage: z.number().nullable().optional(),
});
