import React, { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { api } from '../services/api';
import { useClassroomRealtime } from '../hooks/useClassroomRealtime';

type ClassroomQuestion = { questionId: string; text: string; options: string[]; type: string };

export const ClassroomTeacherConsole: React.FC = () => {
  const { sessionId = '' } = useParams();
  const navigate = useNavigate();
  const [data, setData] = useState<any>(null); const [message, setMessage] = useState('');
  const [schoolId, setSchoolId] = useState(''); const [classId, setClassId] = useState('');
  const [questions, setQuestions] = useState<ClassroomQuestion[]>([]); const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const load = useCallback(async () => { if (!sessionId) return; try { setData(await api.getClassroomAggregate(sessionId)); } catch { setMessage('تعذر قراءة حالة الجلسة.'); } }, [sessionId]);
  useEffect(() => { void load(); }, [load]); useClassroomRealtime(sessionId, load);
  const loadQuestions = async () => { try { const result = await api.getClassroomQuestions(schoolId); setQuestions(result.questions); setMessage('اختر من 1 إلى 10 أسئلة معتمدة.'); } catch { setMessage('تعذر تحميل بنك الأسئلة. تحقق من المدرسة وصلاحية الإسناد.'); } };
  const create = async () => { try { const result = await api.createClassroomSession({ schoolId, classId, questionIds: selectedIds }); setMessage(`تم إنشاء الحصة. رمز الانضمام: ${result.pin}`); navigate(`/classroom/${result.sessionId}/teacher`); } catch { setMessage('تعذر إنشاء الحصة. يجب اختيار فصل مسند وأسئلة معتمدة.'); } };
  const publish = async () => { const index = Number(window.prompt('رقم السؤال من ترتيب الحصة (يبدأ من 0)')); if (!Number.isInteger(index)) return; try { await api.publishClassroomQuestion(sessionId, index); await load(); } catch { setMessage('تعذر نشر السؤال.'); } };
  const end = async () => { try { const result = await api.endClassroomSession(sessionId); setData((current: any) => ({ ...current, report: result.report, status: 'ended' })); setMessage('تم إنهاء الجلسة وتثبيت التقرير.'); } catch { setMessage('تعذر إنهاء الجلسة.'); } };
  if (!sessionId) return <main className="mx-auto max-w-4xl p-6" dir="rtl"><h1 className="text-3xl font-black">ابدأ فصلًا ذكيًا</h1><p className="mt-2 text-slate-500">اختر فصلًا مسندًا لك ثم أسئلة معتمدة من بنك المنصة الحالي.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><input value={schoolId} onChange={(event) => setSchoolId(event.target.value)} className="rounded-xl border p-3" placeholder="معرّف المدرسة" /><input value={classId} onChange={(event) => setClassId(event.target.value)} className="rounded-xl border p-3" placeholder="معرّف الفصل" /></div><button type="button" onClick={() => void loadQuestions()} disabled={!schoolId} className="mt-3 rounded-xl bg-slate-800 px-5 py-3 font-black text-white disabled:opacity-50">عرض الأسئلة المعتمدة</button>{questions.length > 0 && <div className="mt-6 space-y-3">{questions.map((question) => <label key={question.questionId} className="flex cursor-pointer gap-3 rounded-xl border p-4"><input type="checkbox" checked={selectedIds.includes(question.questionId)} onChange={() => setSelectedIds((ids) => ids.includes(question.questionId) ? ids.filter((id) => id !== question.questionId) : ids.length < 10 ? [...ids, question.questionId] : ids)} /><span><b>{question.text}</b><small className="mt-1 block text-slate-500">{question.type} · {question.options.length} خيارات</small></span></label>)}</div>}<button type="button" onClick={() => void create()} disabled={!schoolId || !classId || !selectedIds.length} className="mt-6 rounded-xl bg-indigo-600 px-5 py-3 font-black text-white disabled:opacity-50">إنشاء الحصة ({selectedIds.length}/10)</button><p className="mt-4 text-sm text-slate-600">{message}</p></main>;
  return <main className="mx-auto max-w-4xl p-6" dir="rtl"><h1 className="text-3xl font-black">لوحة تحكم المعلم</h1><p className="mt-2 text-slate-500">الحالة: {data?.status || '...'}</p><p className="mt-2 text-sm text-slate-500">رابط الطلاب: /classroom/{sessionId} · رابط العرض: /classroom/{sessionId}/projector</p><div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-slate-100 p-5"><b>الإجابات</b><div className="text-3xl font-black">{data?.responseCount ?? 0}</div></div><div className="rounded-2xl bg-slate-100 p-5"><b>السؤال الحالي</b><div className="text-3xl font-black">{data?.activeQuestionIndex ?? '-'}</div></div><div className="rounded-2xl bg-slate-100 p-5"><b>التوزيع</b><div className="mt-2 text-sm">{JSON.stringify(data?.distribution || {})}</div></div></div><div className="mt-6 flex gap-3"><button onClick={() => void publish()} disabled={data?.status === 'ended'} className="rounded-xl bg-indigo-600 px-5 py-3 font-black text-white disabled:opacity-50">نشر سؤال</button><button onClick={() => void end()} disabled={data?.status === 'ended'} className="rounded-xl bg-rose-600 px-5 py-3 font-black text-white disabled:opacity-50">إنهاء الجلسة</button></div><p className="mt-4 text-sm text-slate-600">{message}</p></main>;
};
