import assert from 'node:assert/strict';
import { QuizResultModel } from '../models/QuizResult.js';
import { QuizRetakeModel } from '../modules/quizzes/infrastructure/quizRetakeModel.js';

export const verifyQuizAvailabilityJourney = async ({ request, csrf, adminToken, studentToken, outsiderToken, studentId, outsiderId, pathId, subjectId, questionId, quizId }: any) => {
  assert.equal(process.env.NODE_ENV, 'test');
  assert.match(process.env.MONGODB_URI || '', /^mongodb:\/\/(127\.0\.0\.1|localhost):27017\/almeaa_platform_v3_ci_/);
  const iso = (delta: number) => new Date(Date.now() + delta).toISOString();
  const write = (path: string, body: any, token = adminToken, method = 'POST') => request(path, { method, token, csrf, body });
  const submit = () => write(`/quizzes/${quizId}/submit`, { answers: { [questionId]: 1 }, timeSpentSeconds: 1, source: 'tests' }, studentToken);
  const start = () => write('/live-exams/start', { quizId, totalQuestions: 1 }, studentToken);
  const grant = (studentIds: string[], opensAt = iso(-1000)) => write(`/quizzes/${quizId}/retakes`, { studentIds, opensAt, closesAt: iso(86400000) });
  const created = await write('/quizzes', { id: quizId, title: 'Window and selective retake fixture', pathId, subjectId, questionIds: [questionId], targetUserIds: [studentId], isPublished: true, access: { type: 'free' }, settings: { maxAttempts: 1, timeLimit: 45 }, opensAt: iso(3600000), closesAt: iso(86400000) });
  assert.equal(created.status, 201);
  assert.equal((await request(`/quizzes/${quizId}`, { token: studentToken })).body.questions.length, 0);
  assert.equal((await start()).status, 403);
  assert.equal((await submit()).status, 403);
  assert.equal((await write(`/quizzes/${quizId}`, { closesAt: iso(1000) }, adminToken, 'PATCH')).status, 400);
  assert.equal((await write(`/quizzes/${quizId}`, { opensAt: iso(-1000) }, adminToken, 'PATCH')).status, 200);
  assert.equal((await start()).status, 200);
  assert.equal((await submit()).status, 201);
  const oldResult = await QuizResultModel.findOne({ quizId, userId: studentId }).lean();
  assert.ok(oldResult);
  const before = JSON.stringify(oldResult);
  assert.equal((await write('/live-exams/end', { quizId }, studentToken)).status, 200);
  assert.equal((await start()).status, 409);
  assert.equal((await write(`/quizzes/${quizId}`, { opensAt: null, closesAt: iso(-1000) }, adminToken, 'PATCH')).status, 200);
  assert.equal((await request(`/live-exams/session/${quizId}`, { token: studentToken })).status, 403);
  assert.equal((await write('/live-exams/progress', { quizId, answers: {} }, studentToken)).status, 403);
  assert.equal((await grant([outsiderId])).status, 403);
  assert.equal((await write(`/quizzes/${quizId}/retakes`, { studentIds: [studentId], opensAt: iso(-1000), closesAt: iso(86400000) }, studentToken)).status, 403);
  assert.equal(await QuizRetakeModel.countDocuments({ quizId }), 0);
  assert.equal((await grant([studentId], iso(3600000))).status, 200);
  assert.equal((await start()).status, 403);
  assert.equal((await grant([studentId])).status, 200);
  const retried = await Promise.all([grant([studentId]), grant([studentId])]);
  assert.ok(retried.every(r => r.status === 200));
  assert.equal((await QuizRetakeModel.findOne({ quizId, studentId }).lean())?.maxAttempts, 2);
  assert.equal(await QuizRetakeModel.countDocuments({ quizId }), 1);
  const detail = await request(`/quizzes/${quizId}`, { token: studentToken });
  assert.equal(detail.body.viewerRetakeGranted, true);
  assert.equal(detail.body.settings.maxAttempts, 2);
  assert.equal(detail.body.questions.length, 1);
  const metadata = await request(`/quizzes/${quizId}?includeQuestions=false`, { token: studentToken });
  assert.equal(metadata.body.questions.length, 0);
  assert.equal(metadata.body.viewerRetakeGranted, true);
  assert.equal(metadata.body.settings.maxAttempts, 2);
  assert.equal((await request(`/quizzes/${quizId}`, { token: outsiderToken })).status, 403);
  assert.equal((await start()).status, 200);
  assert.equal((await submit()).status, 201);
  assert.equal((await submit()).status, 409);
  assert.equal(await QuizResultModel.countDocuments({ quizId, userId: studentId }), 2);
  assert.equal(JSON.stringify(await QuizResultModel.findById(oldResult._id).lean()), before);
  console.log('Assessment windows + selective retakes + immutable prior outcome: PASS');
};
